# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f865d6dbcdd626f40d0930fd90859bb7a60e501bd9442efe95430dbaed37b5ece16d68ff77f482b471bcb03e46b246b928ffb89b357e524fbf4a17ad7d6898

test:
  secret_key_base: 42bcc49dd90f117832bc140bc2fa5e9ad0a40e94ad112e6f6d88b8619069b013502f0c800154980168abb95d4c6b192ece18c5ff16527733b32aca61d45d4db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
