#!/usr/bin/env bash

if
  [[ -s "/home/chaitanyareddy/.rvm/gems/ruby-2.3.1/environment" ]]
then
  source "/home/chaitanyareddy/.rvm/gems/ruby-2.3.1/environment"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/chaitanyareddy/.rvm/gems/ruby-2.3.1/environment'" >&2
  exit 1
fi
