# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ab8f083d3910b9091f1b5b6703cffc6169a5faba31288f7adc7926acc7df6bfeccc10d0349cdf66629b25b1e390e6202a729e2320305836ac422a2cba2367a

test:
  secret_key_base: d00dd85bf7bef1145bd06918edd9ef3a2fbe50308f8c922a7e51204ed6e15c0abbd7327e24ddfb17f86cb7353c4a12d31b772f4d389387f2f3503b89682d1139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
