# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b26fa434ebb80d4b11bfe7f2f27b1646757068e1363ecd87a72e81ded858debd37739b6c87fc7a2b037b17f124137fcbe3b9253a3a4f910a438a6f757c46721

test:
  secret_key_base: 70bb81dbb6b970024fb10981440bf235257b13b6c690f1574c8e5d50cfb655933c5ea80e75cb748b89d6fb836268a2086f99dd18ebc39531cefebc88204edc31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
