# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55372c81df156cba5ee6c04acef611440333189b46cb19271de9285dc6c87380ef79d034fe9f46cd28c6cdb3cf7fd0eca7841eee3da21d33775ae34b8439f76b

test:
  secret_key_base: bd2ce38185ae10dc2205420be9247a387ba0c5c96c6d82619892b39d72174787cab0268d035863cc2d6dcf44d83773af91e9b48c971e246682ef8ec5df5a8d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
