# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac9a06044abc6aa52e4cb6e5cf56e375650fcf9c28e0c008b9b9cf56e39a158377c6e3f31852b90a887d0d3db7ba2731257bb5b52e95bdbb88c070f3b9200750

test:
  secret_key_base: 6b4a2606a3a8f0615d28d51981cd304d1aa13f45c9ec082d398a5da596b2a1f702518060b85e8c33837e29555a91915fd778d1d9863ed30c6866c5fe87e04cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
